development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: apostell_database_development
  pool:     5
  username: postgres
  password: postgres
  template: template0
  timeout: 5000
  
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: apostell_database_test
  pool:     5
  username: postgres
  password: postgres
  template: template0
  timeout: 5000

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: apostell_database_production
  pool:     5
  username: postgres
  password: postgres
  template: template0
  timeout: 5000
